-- AlterTable
ALTER TABLE `order_tracking` MODIFY `status` ENUM('PENDING', 'ACCEPTED', 'REJECTED', 'SHIPPED', 'DELIVERED', 'CANCELLED') NOT NULL;

-- AlterTable
ALTER TABLE `orders` ADD COLUMN `cancelReason` VARCHAR(500) NULL,
    MODIFY `status` ENUM('PENDING', 'ACCEPTED', 'REJECTED', 'SHIPPED', 'DELIVERED', 'CANCELLED') NOT NULL DEFAULT 'PENDING';
